color:
    when: auto
    theme: custom 
sorting:
  column: name 
  dir-grouping: first
recursion:
    depth: 3
size: short
total-size: false
indicators: false
no-symlink: false
icons:
    when: auto 
date: relative
blocks:
    - permission
    - size
    - date
    - git
    - name
symlink-arrow: ->
